services:
- type: web
  name: nocodb
  env: docker
  autoDeploy: false
  healthCheckPath: /dashboard
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: nocodb
      property: connectionString
  - key: PORT
    value: 8080
  region: frankfurt
databases:
- name: nocodb
  region: frankfurt
