services:
- type: web
  name: nocodb
  env: docker
  autoDeployTrigger: commit
  healthCheckPath: /dashboard
  region: frankfurt
  envVars:
  - key: PORT
    value: 8080
  # Storage for SQLite database
  disk:
    name: nocodb-sqlite
    mountPath: /usr/app/data
    sizeGB: 40
